spring.application.name=tfrrs-race-api
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/your_database_name
spring.datasource.username=Behn
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional: Automatically updates the database schema based on your Java entities
spring.jpa.hibernate.ddl-auto=update
